// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACdy1ifKvkGArNT9jiClhNzcngoQjxMw0',
    appId: '1:256840841104:web:ebf55f80fa249172a02515',
    messagingSenderId: '256840841104',
    projectId: 'my-new-project-56ef3',
    authDomain: 'my-new-project-56ef3.firebaseapp.com',
    storageBucket: 'my-new-project-56ef3.firebasestorage.app',
    measurementId: 'G-9MV2D7K7HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZgG9BCb-hYPG-gnXoXoEUxLOXWzC1GQ',
    appId: '1:256840841104:android:a20a475b5e689cb7a02515',
    messagingSenderId: '256840841104',
    projectId: 'my-new-project-56ef3',
    storageBucket: 'my-new-project-56ef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4g_Q47S7jiod9aDHy8LO75vRB7ppVxM',
    appId: '1:256840841104:ios:478ba608dfc177f8a02515',
    messagingSenderId: '256840841104',
    projectId: 'my-new-project-56ef3',
    storageBucket: 'my-new-project-56ef3.firebasestorage.app',
    iosBundleId: 'com.example.myNewProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN4g_Q47S7jiod9aDHy8LO75vRB7ppVxM',
    appId: '1:256840841104:ios:478ba608dfc177f8a02515',
    messagingSenderId: '256840841104',
    projectId: 'my-new-project-56ef3',
    storageBucket: 'my-new-project-56ef3.firebasestorage.app',
    iosBundleId: 'com.example.myNewProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACdy1ifKvkGArNT9jiClhNzcngoQjxMw0',
    appId: '1:256840841104:web:d8594c353dfc9f9ca02515',
    messagingSenderId: '256840841104',
    projectId: 'my-new-project-56ef3',
    authDomain: 'my-new-project-56ef3.firebaseapp.com',
    storageBucket: 'my-new-project-56ef3.firebasestorage.app',
    measurementId: 'G-TK0WXKN7LC',
  );
}
